name: unit-test
on: [push]

jobs:
  build:
    name: unit-test
    runs-on: macOS-latest
    env:
        GIT_SSL_NO_VERIFY: true
        DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v1
      - name: test
        run: swift test
